# Generated by Django 5.2.5 on 2025-09-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='PhoneBook/static/images/'),
        ),
    ]
