# Generated by Django 5.2.5 on 2025-10-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneBook', '0002_contact_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='.'),
        ),
    ]
