# Generated by Django 5.2.5 on 2025-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysuperuser',
            name='adress',
            field=models.CharField(default=None, max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='mysuperuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mysuperuser',
            name='profile_picture',
            field=models.TextField(default=None, null=True),
        ),
    ]
