# Generated by Django 5.2.5 on 2025-09-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_alter_mysuperuser_adress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysuperuser',
            old_name='adress',
            new_name='address',
        ),
    ]
